[features]
seeds = false
[programs.localnet]
web3_solana = "D2jUdR3ejCMKy9TwkpcNZsj36snszBWQiLdWEryQ8Xdo"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/robert/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
